package com.example

data class LanguageStrings(
    val browse: String,
    val nowPlaying: String,
    val favorites: String,
    val preferences: String,
    val settings: String,
    val about: String,
    val colorTheme: String,
    val crossfade: String,
    val pitchShift: String,
    val sleepTimerFade: String,
    val smoothFadeDesc: String,
    val close: String,
    val lastFmScrobbling: String,
    val lastFmDesc: String,
    val connectLastFm: String,
    val loggedIn: String,
    val logout: String,
    val musicLibrary: String,
    val manageFolders: String,
    val backupRestore: String,
    val export: String,
    val import: String,
    val version: String,
    val developedBy: String,
    val aboutDesc: String,
    val selectLanguage: String,
    val welcomeDesc: String,
    val changeLaterDesc: String,
    val continueBtn: String,
    val appLanguage: String,
    val musicSources: String,
    val sourcesDesc: String,
    val addFolder: String,
    val rescanAll: String,
    val done: String
)

object Localization {
    private val English = LanguageStrings(
        browse = "Browse",
        nowPlaying = "Now Playing",
        favorites = "Favorites",
        preferences = "Preferences",
        settings = "Settings",
        about = "About",
        colorTheme = "Color Theme",
        crossfade = "Crossfade",
        pitchShift = "Pitch Shift",
        sleepTimerFade = "Sleep Timer Fade",
        smoothFadeDesc = "Smoothly fade out when timer ends",
        close = "Close",
        lastFmScrobbling = "Last.fm Scrobbling",
        lastFmDesc = "Log in to scrobble your listening history to Last.fm.",
        connectLastFm = "Connect Last.fm",
        loggedIn = "Logged in",
        logout = "Logout",
        musicLibrary = "Music Library",
        manageFolders = "Manage Music Folders",
        backupRestore = "Backup & Restore",
        export = "Export",
        import = "Import",
        version = "Version",
        developedBy = "Developed By",
        aboutDesc = "A premium glassmorphic audio experience built with Jetpack Compose. Designed for audiophiles who value both aesthetics and performance.",
        selectLanguage = "Select Language",
        welcomeDesc = "Welcome to GlassPlayer! Please choose your preferred language to continue.",
        changeLaterDesc = "You can change this later in Settings.",
        continueBtn = "Continue",
        appLanguage = "App Language",
        musicSources = "Music Sources",
        sourcesDesc = "GlassPlayer scans these folders for audio files. You can add multiple folders from your device or SD card.",
        addFolder = "Add Folder",
        rescanAll = "Rescan All Folders",
        done = "Done"
    )

    private val Spanish = LanguageStrings(
        browse = "Explorar",
        nowPlaying = "Reproduciendo",
        favorites = "Favoritos",
        preferences = "Preferencias",
        settings = "Ajustes",
        about = "Acerca de",
        colorTheme = "Tema de Color",
        crossfade = "Fundido cruzado",
        pitchShift = "Cambio de tono",
        sleepTimerFade = "Desvanecimiento del temporizador",
        smoothFadeDesc = "Desvanecimiento suave al finalizar el temporizador",
        close = "Cerrar",
        lastFmScrobbling = "Scrobbling de Last.fm",
        lastFmDesc = "Inicia sesión para registrar tu historial en Last.fm.",
        connectLastFm = "Conectar Last.fm",
        loggedIn = "Sesión iniciada",
        logout = "Cerrar sesión",
        musicLibrary = "Biblioteca de música",
        manageFolders = "Gestionar carpetas",
        backupRestore = "Copia de seguridad y restauración",
        export = "Exportar",
        import = "Importar",
        version = "Versión",
        developedBy = "Desarrollado por",
        aboutDesc = "Una experiencia de audio glassmorphic premium construida con Jetpack Compose. Diseñado para audiófilos que valoran tanto la estética como el rendimiento.",
        selectLanguage = "Seleccionar idioma",
        welcomeDesc = "¡Bienvenido a GlassPlayer! Por favor, elige tu idioma preferido para continuar.",
        changeLaterDesc = "Puedes cambiar esto más tarde en Ajustes.",
        continueBtn = "Continuar",
        appLanguage = "Idioma de la aplicación",
        musicSources = "Fuentes de música",
        sourcesDesc = "GlassPlayer escanea estas carpetas en busca de archivos. Puedes añadir varias carpetas.",
        addFolder = "Añadir carpeta",
        rescanAll = "Escanear todo",
        done = "Hecho"
    )

    private val French = LanguageStrings(
        browse = "Parcourir",
        nowPlaying = "En lecture",
        favorites = "Favoris",
        preferences = "Préférences",
        settings = "Paramètres",
        about = "À propos",
        colorTheme = "Thème de couleur",
        crossfade = "Fondu enchaîné",
        pitchShift = "Décalage de hauteur",
        sleepTimerFade = "Fondu de mise en veille",
        smoothFadeDesc = "Fondu progressif à la fin de la minuterie",
        close = "Fermer",
        lastFmScrobbling = "Scrobbling Last.fm",
        lastFmDesc = "Connectez-vous pour scrobbler votre historique sur Last.fm.",
        connectLastFm = "Connecter Last.fm",
        loggedIn = "Connecté",
        logout = "Déconnexion",
        musicLibrary = "Bibliothèque musicale",
        manageFolders = "Gérer les dossiers",
        backupRestore = "Sauvegarde & Restauration",
        export = "Exporter",
        import = "Importer",
        version = "Version",
        developedBy = "Développé par",
        aboutDesc = "Une expérience audio glassmorphic premium construite avec Jetpack Compose. Conçu pour les audiophiles qui apprécient à la fois l'esthétique et la performance.",
        selectLanguage = "Choisir la langue",
        welcomeDesc = "Bienvenue sur GlassPlayer ! Veuillez choisir votre langue préférée pour continuer.",
        changeLaterDesc = "Vous pourrez modifier cela plus tard dans les Paramètres.",
        continueBtn = "Continuer",
        appLanguage = "Langue de l'application",
        musicSources = "Sources musicales",
        sourcesDesc = "GlassPlayer scanne ces dossiers. Vous pouvez ajouter plusieurs dossiers.",
        addFolder = "Ajouter un dossier",
        rescanAll = "Tout rescanner",
        done = "Terminé"
    )

    fun getStrings(language: String): LanguageStrings = when (language) {
        "Spanish" -> Spanish
        "French" -> French
        else -> English
    }
}
