package com.example

/**
 * Stable identity and source helpers for local and YouTube tracks.
 *
 * `youtube://VIDEO_ID` is a database identifier only — never a Media3 stream URI.
 */
const val YOUTUBE_URI_PREFIX = "youtube://"
const val YOUTUBE_CATEGORY_PREFIX = "yt:"
const val FOLDER_YOUTUBE = "YouTube"

enum class TrackSource {
    LOCAL,
    YOUTUBE,
    SYNTH
}

enum class PlaylistAddResult {
    ADDED,
    ALREADY_IN_PLAYLIST,
    FAILED
}

fun PlaylistAddResult.userMessage(): String = when (this) {
    PlaylistAddResult.ADDED -> "Added to playlist"
    PlaylistAddResult.ALREADY_IN_PLAYLIST -> "Already in this playlist"
    PlaylistAddResult.FAILED -> "Unable to add song to playlist"
}

fun youtubeTrackUri(videoId: String): String = "$YOUTUBE_URI_PREFIX$videoId"

fun isPlausibleYouTubeVideoId(id: String): Boolean {
    if (id.isBlank() || id.contains('/') || id.contains(' ') || id.contains('.')) return false
    // Typical YouTube IDs are 11 chars; allow a small range.
    if (id.length !in 8..15) return false
    if (id.all { it.isDigit() }) return false
    return id.all { it.isLetterOrDigit() || it == '-' || it == '_' }
}

fun AudioTrackEntity.isYouTubeTrack(): Boolean {
    if (folderName.equals(FOLDER_YOUTUBE, ignoreCase = true)) return true
    if (category.startsWith(YOUTUBE_CATEGORY_PREFIX)) return true
    if (uri.startsWith(YOUTUBE_URI_PREFIX)) return true
    return youtubeVideoId() != null
}

fun AudioTrackEntity.youtubeVideoId(): String? {
    if (category.startsWith(YOUTUBE_CATEGORY_PREFIX)) {
        val id = category.removePrefix(YOUTUBE_CATEGORY_PREFIX).substringBefore("&").substringBefore("?").trim()
        if (isPlausibleYouTubeVideoId(id)) return id
    }
    if (uri.startsWith(YOUTUBE_URI_PREFIX)) {
        val id = uri.removePrefix(YOUTUBE_URI_PREFIX).substringBefore("?").substringBefore("&").trim()
        if (isPlausibleYouTubeVideoId(id)) return id
    }
    if (uri.contains("watch?v=")) {
        val id = uri.substringAfter("watch?v=").substringBefore("&").substringBefore("#").trim()
        if (isPlausibleYouTubeVideoId(id)) return id
    }
    if (uri.contains("youtu.be/")) {
        val id = uri.substringAfter("youtu.be/").substringBefore("?").substringBefore("&").trim()
        if (isPlausibleYouTubeVideoId(id)) return id
    }
    return null
}

fun AudioTrackEntity.trackSource(): TrackSource {
    return when {
        uri == AudioRepository.SYNTH_URI -> TrackSource.SYNTH
        isYouTubeTrack() -> TrackSource.YOUTUBE
        else -> TrackSource.LOCAL
    }
}

/** True when [uri] is a real playable URI for Media3 (not a YouTube identity URI). */
fun AudioTrackEntity.canPlayWithExoPlayer(): Boolean {
    if (trackSource() == TrackSource.YOUTUBE || trackSource() == TrackSource.SYNTH) return false
    val value = uri
    if (value.isBlank()) return false
    if (value.startsWith(YOUTUBE_URI_PREFIX)) return false
    return value.startsWith("http://") ||
        value.startsWith("https://") ||
        value.startsWith("content://") ||
        value.startsWith("file://") ||
        value.startsWith("/")
}

/**
 * Returns a copy safe to insert into Room: autogenerated id, never a blank URI,
 * YouTube identity always `youtube://VIDEO_ID` + `yt:VIDEO_ID`.
 */
fun AudioTrackEntity.normalizedForPersistence(): AudioTrackEntity? {
    val ytId = youtubeVideoId()
    if (ytId != null) {
        val art = albumArtUri?.takeIf { it.isNotBlank() }
            ?: "https://i.ytimg.com/vi/$ytId/hqdefault.jpg"
        return copy(
            id = 0,
            uri = youtubeTrackUri(ytId),
            category = "$YOUTUBE_CATEGORY_PREFIX$ytId",
            folderName = FOLDER_YOUTUBE,
            album = album.ifBlank { "YouTube Music" },
            albumArtUri = art,
            dateAdded = if (dateAdded > 0L) dateAdded else System.currentTimeMillis()
        )
    }
    if (uri.isBlank()) return null
    return copy(
        id = 0,
        dateAdded = if (dateAdded > 0L) dateAdded else System.currentTimeMillis()
    )
}
